import popupWork from "./popupWork.js";
import hideProductListWork from "./hideProductListWork.js";
import addMissingProductList from "./addMissingProductList.js";
import addProductList from "./addProductList.js";
import buttonDeliveryPopupWork from "./buttonDeliveryPopupWork.js";
import deleteProductsBtnWork from "./deleteProductsBtnWork.js";
import counterProductsWork from "./counterProductsWork.js";
import cartTotalCalculation from "./cartTotalCalculation.js";
import counterMissingProducts from "./counterMissingProducts.js";
import counterAvailableProducts from "./counterAvailableProducts.js";
import checkPayNowWork from "./checkPayNowWork.js";
import changePaymentCardWork from "./changePaymentCardWork.js";
import changeAddressDeliveryWork from "./changeAddressDeliveryWork.js";
import deleteDeliveryAddressWork from "./deleteDeliveryAddressWork.js";
import checkProductWork from "./checkProductWork.js";
import cartQuantityCountWork from "./cartQuantityCountWork.js";
import validationInputWork from "./validationInputWork.js";
document.addEventListener('DOMContentLoaded', () => {
    addProductList();
    addMissingProductList();
    popupWork();
    hideProductListWork();
    deleteProductsBtnWork();
    buttonDeliveryPopupWork();
    counterProductsWork();
    cartTotalCalculation();
    counterMissingProducts();
    counterAvailableProducts();
    checkPayNowWork();
    changePaymentCardWork();
    changeAddressDeliveryWork();
    deleteDeliveryAddressWork();
    checkProductWork();
    cartQuantityCountWork();
    validationInputWork();
});